### ISSUE TITLE
memorious issues on all sources 

### ISSUE THREAD

**Issue by Revok-98** [alephdata/opensanctions#35]
Hello,

When running most files like memorious run us_ofac, we get the following error:

Any idea how to solve it ?

Error:
INFO:ca_dfatd_sema_sanctions.store:[ca_dfatd_sema_sanctions->store(balkhash_put)]: 393ae9b89d8e11e98d580242ac110002
ERROR:ca_dfatd_sema_sanctions.store:'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
  File "/memorious/memorious/logic/context.py", line 75, in execute
    return self.stage.method(self, data)
  File "/usr/lib/python3.7/site-packages/balkhash/memorious.py", line 21, in balkhash_put
    writer = get_dataset(context)
  File "/usr/lib/python3.7/site-packages/balkhash/memorious.py", line 15, in get_dataset
    return init(**config)
  File "/usr/lib/python3.7/site-packages/balkhash/__init__.py", line 5, in init
    backend = backend.upper()
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by alexmojaki** [comment]
I just ran into this as well, made some contributions which helped. Check out the new README.

**Comment by pudo** [comment]
FIxed, thanks to @alexmojaki
