### ISSUE TITLE
Error in `balkhash iterate -d us_ofac` after crawling

### ISSUE THREAD

**Issue by alexmojaki** [alephdata/opensanctions#40]
`memorious run us_ofac` works, but it seems to be producing some invalid data, because afterwards `balkhash iterate -d $crawler` fails with the error:

```
Traceback (most recent call last):
  File "/usr/bin/balkhash", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/balkhash/cli.py", line 55, in iterate
    for entity in dataset.iterate(entity_id=entity):
  File "/usr/lib/python3.7/site-packages/balkhash/dataset.py", line 50, in iterate
    entity.merge(partial)
  File "/usr/lib/python3.7/site-packages/followthemoney/proxy.py", line 267, in merge
    self.schema = model.common_schema(self.schema, other.schema)
  File "/usr/lib/python3.7/site-packages/followthemoney/model.py", line 89, in common_schema
    raise InvalidData(msg % (left, right))
followthemoney.exc.InvalidData: No common ancestor: <Schema('Ownership')> and <Schema('Person')>
```

The error goes away if I prevent the crawler from emitting any Ownership objects.

**Comment by pudo** [comment]
I've just confirmed that this is fixed after the merge.
