### ISSUE TITLE
`aleph_emit` method not available

### ISSUE THREAD

**Issue by ChrisjanWust** [alephdata/opensanctions#70]
The `aleph_emit` does not seem to be available where it is used in the `eu_eeas_sanctions` source:

```
worker_1    | INFO:eu_eeas_sanctions.emit_doc:[eu_eeas_sanctions->emit_doc(aleph_emit)]: 0a37407ce59d44d6bf7648fb11ab312c
worker_1    | ERROR:eu_eeas_sanctions.emit_doc:('Unknown method: %s', 'aleph_emit')
worker_1    | Traceback (most recent call last):
worker_1    |   File "/memorious/memorious/logic/context.py", line 77, in execute
worker_1    |     return self.stage.method(self, data)
worker_1    |   File "/memorious/memorious/logic/stage.py", line 26, in method
worker_1    |     raise ValueError("Unknown method: %s", self.method_name)
worker_1    | ValueError: ('Unknown method: %s', 'aleph_emit')
```

**Comment by ChrisjanWust** [comment]
Not relevant anymore.
