### ISSUE TITLE
Exception when exporting `eu_eeas_sanctions` to Aleph

### ISSUE THREAD

**Issue by haarts** [alephdata/opensanctions#71]
When exporting the results of the `eu_eeas_sanctions` an exception is thrown and the process crashes. This is with the latest master (8ec6faf9618b29aeb8c5bebfb1a08cbef71b2e99). No changes have been made to the code. The export process was taken from the README:
 
```
/ # ftm store iterate -d eu_eeas_sanctions   | alephclient write-entities -f   eu_eeas_sanctions
INFO:alephclient.cli:[eu_eeas_sanctions] Bulk load entities: 1000...
INFO:alephclient.cli:[eu_eeas_sanctions] Bulk load entities: 2000...
INFO:alephclient.cli:[eu_eeas_sanctions] Bulk load entities: 3000...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/followthemoney/proxy.py", line 247, in merge
    self.schema = model.common_schema(self.schema, other.schema)
  File "/usr/lib/python3.8/site-packages/followthemoney/model.py", line 94, in common_schema
    raise InvalidData(msg % (left, right))
followthemoney.exc.InvalidData: No common schema: <Schema('Organization')> and <Schema('Person')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ftm", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/ftmstore/cli.py", line 66, in iterate
    iterate_stream(dataset, outfile)
  File "/usr/lib/python3.8/site-packages/ftmstore/cli.py", line 31, in iterate_stream
    for entity in dataset.iterate(entity_id=entity_id):
  File "/usr/lib/python3.8/site-packages/ftmstore/dataset.py", line 134, in iterate
    entity.merge(partial)
  File "/usr/lib/python3.8/site-packages/followthemoney/proxy.py", line 250, in merge
    raise InvalidData(msg % (self.id, e))
followthemoney.exc.InvalidData: Cannot merge entities with id eeas-116106: No common schema: <Schema('Organization')> and <Schema('Person')>
```

**Comment by sunu** [comment]
We faced this issue in our instance too. Some of the new entities produce ids that clash with old ones. We cleared the existing older data and loaded the new data only to avoid the id clash.

**Comment by pudo** [comment]
I think this was the keying error, let's close unless the problem continues to happen after the store has been cleared.
